apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "zzzzz6"
  links:
    - url: https://confluent.cloud
      title: Confluent Cloud Console
      icon: dashboard
  annotations:
    github.com/project-slug: dwessendorf/cc-cluster-zzzzz6
    backstage.io/techdocs-ref: dir:.
spec:
  type: confluent-cluster
  owner: group:guests
  lifecycle: experimental
  system: confluent-cloud
  dependsOn: 
    - component:zzzzz